kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
  - role: worker
  - role: worker
networking:
  disableDefaultCNI: true   # 기본 CNI 비활성화 (Calico 설치 예정)
  podSubnet: "192.168.0.0/16"

